"""add user_id to reports

Revision ID: 36db7033172e
Revises: 861faf7122dc
Create Date: 2026-02-11 20:37:11.638659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36db7033172e'
down_revision: Union[str, Sequence[str], None] = '861faf7122dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_column('reports', 'user_id')
    # ### end Alembic commands ###
