"""add reports table

Revision ID: 861faf7122dc
Revises: 15f6f610af8f
Create Date: 2026-02-11 00:43:58.006567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861faf7122dc'
down_revision: Union[str, Sequence[str], None] = '15f6f610af8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=120), nullable=True),
    sa.Column('reviews_text', sa.Text(), nullable=False),
    sa.Column('ratings_csv', sa.String(length=200), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Integer(), nullable=False),
    sa.Column('shareability', sa.Integer(), nullable=False),
    sa.Column('growth', sa.Integer(), nullable=False),
    sa.Column('risk', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
